In [1]:
import pandas as pd

df = pd.read_excel(
    "/content/curriculum_industry_skill_gap_dataset_800.xlsx"
)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

display(df.head())

Dataset loaded successfully!
Shape: (800, 27)

Columns:
['Student_ID', 'event_timestamp', 'Programming', 'DSA', 'DBMS', 'Computer_Networks', 'Operating_Systems', 'Web_Development', 'Data_Analytics', 'AI_ML', 'Cloud_Computing', 'Cybersecurity', 'Problem_Solving', 'Aptitude', 'Communication', 'Teamwork', 'Git_GitHub', 'technical_skill_average', 'programming_problem_solving', 'data_ai_average', 'cloud_security_average', 'soft_skill_average', 'overall_skill_average', 'Overall_Industry_Gap', 'Curriculum_Alignment_Score', 'Industry_Alignment_Score', 'Skill_Gap_Category']

,Student_ID,event_timestamp,Programming,DSA,DBMS,Computer_Networks,Operating_Systems,Web_Development,Data_Analytics,AI_ML,...,technical_skill_average,programming_problem_solving,data_ai_average,cloud_security_average,soft_skill_average,overall_skill_average,Overall_Industry_Gap,Curriculum_Alignment_Score,Industry_Alignment_Score,Skill_Gap_Category
0,S0001,2025-01-01 00:00:00,82.40,68.31,62.46,69.62,59.18,75.52,68.26,70.93,...,69.055,71.773333,69.595,66.935,77.25,69.491333,36.74,66.67,72.88,Medium Gap
1,S0002,2025-01-01 01:00:00,60.42,73.44,61.66,62.89,57.78,61.55,60.13,51.74,...,60.079,62.180000,55.935,55.590,57.68,59.164000,38.08,59.65,53.20,Medium Gap
2,S0003,2025-01-01 02:00:00,76.93,66.25,66.15,72.07,69.23,60.51,70.14,66.78,...,69.097,73.906667,68.460,71.455,77.97,71.356667,27.40,76.02,76.02,Medium Gap
3,S0004,2025-01-01 03:00:00,84.16,77.13,80.88,93.83,85.58,78.95,93.06,86.86,...,84.094,84.443333,89.960,80.245,87.34,84.968000,15.64,88.71,87.82,Low Gap
4,S0005,2025-01-01 04:00:00,59.81,55.38,73.78,49.15,44.42,58.36,63.49,62.41,...,57.505,60.170000,62.950,54.125,67.47,60.308000,35.76,62.05,59.82,Medium Gap

In [2]:
print("Dataset Information")
print("===================")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nMissing values:")
print(df.isnull().sum())

print("\nData types:")
print(df.dtypes)

Dataset Information
===================
Rows: 800
Columns: 27

Missing values:
Student_ID                     0
event_timestamp                0
Programming                    0
DSA                            0
DBMS                           0
Computer_Networks              0
Operating_Systems              0
Web_Development                0
Data_Analytics                 0
AI_ML                          0
Cloud_Computing                0
Cybersecurity                  0
Problem_Solving                0
Aptitude                       0
Communication                  0
Teamwork                       0
Git_GitHub                     0
technical_skill_average        0
programming_problem_solving    0
data_ai_average                0
cloud_security_average         0
soft_skill_average             0
overall_skill_average          0
Overall_Industry_Gap           0
Curriculum_Alignment_Score     0
Industry_Alignment_Score       0
Skill_Gap_Category             0
dtype: int64

Data types:
Student_ID                             object
event_timestamp                datetime64[ns]
Programming                           float64
DSA                                   float64
DBMS                                  float64
Computer_Networks                     float64
Operating_Systems                     float64
Web_Development                       float64
Data_Analytics                        float64
AI_ML                                 float64
Cloud_Computing                       float64
Cybersecurity                         float64
Problem_Solving                       float64
Aptitude                              float64
Communication                         float64
Teamwork                              float64
Git_GitHub                            float64
technical_skill_average               float64
programming_problem_solving           float64
data_ai_average                       float64
cloud_security_average                float64
soft_skill_average                    float64
overall_skill_average                 float64
Overall_Industry_Gap                  float64
Curriculum_Alignment_Score            float64
Industry_Alignment_Score              float64
Skill_Gap_Category                     object
dtype: object

In [4]:
feature_df = df[
    [
        "Student_ID",
        "Programming",
        "DSA",
        "DBMS",
        "Computer_Networks",
        "Operating_Systems",
        "Web_Development",
        "Data_Analytics",
        "AI_ML",
        "Cloud_Computing",
        "Cybersecurity",
        "Problem_Solving",
        "Aptitude",
        "Communication",
        "Teamwork",
        "Git_GitHub"
    ]
].copy()

print("Feature dataset created!")
print("Shape:", feature_df.shape)

display(feature_df.head())

Feature dataset created!
Shape: (800, 16)

,Student_ID,Programming,DSA,DBMS,Computer_Networks,Operating_Systems,Web_Development,Data_Analytics,AI_ML,Cloud_Computing,Cybersecurity,Problem_Solving,Aptitude,Communication,Teamwork,Git_GitHub
0,S0001,82.40,68.31,62.46,69.62,59.18,75.52,68.26,70.93,68.21,65.66,64.61,51.18,72.38,82.12,81.53
1,S0002,60.42,73.44,61.66,62.89,57.78,61.55,60.13,51.74,58.65,52.53,52.68,73.48,63.36,52.00,45.15
2,S0003,76.93,66.25,66.15,72.07,69.23,60.51,70.14,66.78,76.39,66.52,78.54,74.78,85.85,70.09,70.12
3,S0004,84.16,77.13,80.88,93.83,85.58,78.95,93.06,86.86,73.73,86.76,92.04,81.91,87.45,87.23,84.95
4,S0005,59.81,55.38,73.78,49.15,44.42,58.36,63.49,62.41,41.03,67.22,65.32,68.44,58.93,76.01,60.87

In [5]:
feature_df["technical_skill_average"] = feature_df[
    [
        "Programming",
        "DSA",
        "DBMS",
        "Computer_Networks",
        "Operating_Systems",
        "Web_Development",
        "Data_Analytics",
        "AI_ML",
        "Cloud_Computing",
        "Cybersecurity"
    ]
].mean(axis=1)

feature_df["programming_problem_solving"] = feature_df[
    ["Programming", "DSA", "Problem_Solving"]
].mean(axis=1)

feature_df["data_ai_average"] = feature_df[
    ["Data_Analytics", "AI_ML"]
].mean(axis=1)

feature_df["cloud_security_average"] = feature_df[
    ["Cloud_Computing", "Cybersecurity"]
].mean(axis=1)

feature_df["soft_skill_average"] = feature_df[
    ["Communication", "Teamwork"]
].mean(axis=1)

feature_df["overall_skill_average"] = feature_df[
    [
        "Programming",
        "DSA",
        "DBMS",
        "Computer_Networks",
        "Operating_Systems",
        "Web_Development",
        "Data_Analytics",
        "AI_ML",
        "Cloud_Computing",
        "Cybersecurity",
        "Problem_Solving",
        "Aptitude",
        "Communication",
        "Teamwork",
        "Git_GitHub"
    ]
].mean(axis=1)

print("Feature engineering completed!")
display(feature_df.head())

Feature engineering completed!

,Student_ID,Programming,DSA,DBMS,Computer_Networks,Operating_Systems,Web_Development,Data_Analytics,AI_ML,Cloud_Computing,...,Aptitude,Communication,Teamwork,Git_GitHub,technical_skill_average,programming_problem_solving,data_ai_average,cloud_security_average,soft_skill_average,overall_skill_average
0,S0001,82.40,68.31,62.46,69.62,59.18,75.52,68.26,70.93,68.21,...,51.18,72.38,82.12,81.53,69.055,71.773333,69.595,66.935,77.25,69.491333
1,S0002,60.42,73.44,61.66,62.89,57.78,61.55,60.13,51.74,58.65,...,73.48,63.36,52.00,45.15,60.079,62.180000,55.935,55.590,57.68,59.164000
2,S0003,76.93,66.25,66.15,72.07,69.23,60.51,70.14,66.78,76.39,...,74.78,85.85,70.09,70.12,69.097,73.906667,68.460,71.455,77.97,71.356667
3,S0004,84.16,77.13,80.88,93.83,85.58,78.95,93.06,86.86,73.73,...,81.91,87.45,87.23,84.95,84.094,84.443333,89.960,80.245,87.34,84.968000
4,S0005,59.81,55.38,73.78,49.15,44.42,58.36,63.49,62.41,41.03,...,68.44,58.93,76.01,60.87,57.505,60.170000,62.950,54.125,67.47,60.308000

In [6]:
# Add industry-related features and timestamp

feature_df["overall_industry_gap"] = df["Overall_Industry_Gap"]

feature_df["curriculum_alignment_score"] = df[
    "Curriculum_Alignment_Score"
]

feature_df["industry_alignment_score"] = df[
    "Industry_Alignment_Score"
]

# Feast requires an entity column called student_id
feature_df = feature_df.rename(
    columns={"Student_ID": "student_id"}
)

# Timestamp for Feast
feature_df["event_timestamp"] = df["event_timestamp"]

print("Feast dataset prepared!")
print("Shape:", feature_df.shape)

display(feature_df.head())

Feast dataset prepared!
Shape: (800, 26)

,student_id,Programming,DSA,DBMS,Computer_Networks,Operating_Systems,Web_Development,Data_Analytics,AI_ML,Cloud_Computing,...,technical_skill_average,programming_problem_solving,data_ai_average,cloud_security_average,soft_skill_average,overall_skill_average,overall_industry_gap,curriculum_alignment_score,industry_alignment_score,event_timestamp
0,S0001,82.40,68.31,62.46,69.62,59.18,75.52,68.26,70.93,68.21,...,69.055,71.773333,69.595,66.935,77.25,69.491333,36.74,66.67,72.88,2025-01-01 00:00:00
1,S0002,60.42,73.44,61.66,62.89,57.78,61.55,60.13,51.74,58.65,...,60.079,62.180000,55.935,55.590,57.68,59.164000,38.08,59.65,53.20,2025-01-01 01:00:00
2,S0003,76.93,66.25,66.15,72.07,69.23,60.51,70.14,66.78,76.39,...,69.097,73.906667,68.460,71.455,77.97,71.356667,27.40,76.02,76.02,2025-01-01 02:00:00
3,S0004,84.16,77.13,80.88,93.83,85.58,78.95,93.06,86.86,73.73,...,84.094,84.443333,89.960,80.245,87.34,84.968000,15.64,88.71,87.82,2025-01-01 03:00:00
4,S0005,59.81,55.38,73.78,49.15,44.42,58.36,63.49,62.41,41.03,...,57.505,60.170000,62.950,54.125,67.47,60.308000,35.76,62.05,59.82,2025-01-01 04:00:00

In [7]:
# Install Parquet support
!pip install -q pyarrow

import os
import shutil

# Create Feast project folders
os.makedirs("/content/feature_repo/data", exist_ok=True)

# Save feature dataset as Parquet
feature_df.to_parquet(
    "/content/student_features.parquet",
    index=False
)

# Copy Parquet into Feast project
shutil.copy(
    "/content/student_features.parquet",
    "/content/feature_repo/data/student_features.parquet"
)

print("✅ Parquet file created!")
print("✅ Copied to Feast data folder!")

print("\nFiles:")
print(os.listdir("/content/feature_repo/data"))

✅ Parquet file created!
✅ Copied to Feast data folder!

Files:
['student_features.parquet']

In [8]:
import os

# Create feature_store.yaml
yaml_code = """
project: curriculum_industry_skillgap
provider: local

registry:
    path: data/registry.db

offline_store:
    type: file

online_store:
    type: sqlite
    path: data/online_store.db
"""

with open("/content/feature_repo/feature_store.yaml", "w") as f:
    f.write(yaml_code)

print("✅ feature_store.yaml created!")

✅ feature_store.yaml created!

In [9]:
%%writefile /content/feature_repo/features.py

from datetime import timedelta

from feast import Entity, FeatureView, Field, FileSource
from feast.types import Float32


# 1. ENTITY

student = Entity(
    name="student_id",
    join_keys=["student_id"],
    description="Unique identifier for each CSE student"
)


# 2. DATA SOURCE

student_features_source = FileSource(
    name="student_features_source",
    path="data/student_features.parquet",
    timestamp_field="event_timestamp"
)


# 3. FEATURE VIEW

student_skill_features = FeatureView(
    name="student_skill_features",
    entities=[student],
    ttl=timedelta(days=365),

    schema=[
        Field(name="Programming", dtype=Float32),
        Field(name="DSA", dtype=Float32),
        Field(name="DBMS", dtype=Float32),
        Field(name="Computer_Networks", dtype=Float32),
        Field(name="Operating_Systems", dtype=Float32),
        Field(name="Web_Development", dtype=Float32),
        Field(name="Data_Analytics", dtype=Float32),
        Field(name="AI_ML", dtype=Float32),
        Field(name="Cloud_Computing", dtype=Float32),
        Field(name="Cybersecurity", dtype=Float32),
        Field(name="Problem_Solving", dtype=Float32),
        Field(name="Aptitude", dtype=Float32),
        Field(name="Communication", dtype=Float32),
        Field(name="Teamwork", dtype=Float32),
        Field(name="Git_GitHub", dtype=Float32),

        Field(name="technical_skill_average", dtype=Float32),
        Field(name="programming_problem_solving", dtype=Float32),
        Field(name="data_ai_average", dtype=Float32),
        Field(name="cloud_security_average", dtype=Float32),
        Field(name="soft_skill_average", dtype=Float32),
        Field(name="overall_skill_average", dtype=Float32),
        Field(name="overall_industry_gap", dtype=Float32),
        Field(name="curriculum_alignment_score", dtype=Float32),
        Field(name="industry_alignment_score", dtype=Float32),
    ],

    source=student_features_source,
)

print("features.py created successfully!")

Writing /content/feature_repo/features.py

In [11]:
!pip install -q feast

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 54.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 82.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 62.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 34.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.

In [12]:
!feast --version

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
Usage: feast [OPTIONS] COMMAND [ARGS]...
Try 'feast --help' for help.

Error: No such option '--version'.

In [13]:
%cd /content/feature_repo
!feast apply

/content/feature_repo
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/feature_repo/features.py:10: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'student_id'.
  student = Entity(
features.py created successfully!
No project found in the repository. Using project name curriculum_industry_skillgap defined in feature_store.yaml
Applying changes for project curriculum_industry_skillgap
Created project curriculum_industry_skillgap
Created entity student_id
Created feature view student_skill_features

Created sqlite table curriculum_industry_skillgap_student_skill_features

In [14]:
from feast import FeatureStore

store = FeatureStore(
    repo_path="/content/feature_repo"
)

feature_refs = [
    "student_skill_features:Programming",
    "student_skill_features:DSA",
    "student_skill_features:DBMS",
    "student_skill_features:Computer_Networks",
    "student_skill_features:Operating_Systems",
    "student_skill_features:Web_Development",
    "student_skill_features:Data_Analytics",
    "student_skill_features:AI_ML",
    "student_skill_features:Cloud_Computing",
    "student_skill_features:Cybersecurity",
    "student_skill_features:Problem_Solving",
    "student_skill_features:Aptitude",
    "student_skill_features:Communication",
    "student_skill_features:Teamwork",
    "student_skill_features:Git_GitHub",
    "student_skill_features:technical_skill_average",
    "student_skill_features:programming_problem_solving",
    "student_skill_features:data_ai_average",
    "student_skill_features:cloud_security_average",
    "student_skill_features:soft_skill_average",
    "student_skill_features:overall_skill_average",
    "student_skill_features:overall_industry_gap",
    "student_skill_features:curriculum_alignment_score",
    "student_skill_features:industry_alignment_score"
]

entity_df = feature_df[
    ["student_id", "event_timestamp"]
].copy()

historical_df = store.get_historical_features(
    entity_df=entity_df,
    features=feature_refs
).to_df()

print("✅ HISTORICAL FEATURE RETRIEVAL SUCCESSFUL")
print("Shape:", historical_df.shape)

display(historical_df.head())

✅ HISTORICAL FEATURE RETRIEVAL SUCCESSFUL
Shape: (800, 26)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,event_timestamp,Programming,DSA,DBMS,Computer_Networks,Operating_Systems,Web_Development,Data_Analytics,AI_ML,...,Git_GitHub,technical_skill_average,programming_problem_solving,data_ai_average,cloud_security_average,soft_skill_average,overall_skill_average,overall_industry_gap,curriculum_alignment_score,industry_alignment_score
0,S0001,2025-01-01 00:00:00+00:00,82.40,68.31,62.46,69.62,59.18,75.52,68.26,70.93,...,81.53,69.055,71.773333,69.595,66.935,77.25,69.491333,36.74,66.67,72.88
1,S0002,2025-01-01 01:00:00+00:00,60.42,73.44,61.66,62.89,57.78,61.55,60.13,51.74,...,45.15,60.079,62.180000,55.935,55.590,57.68,59.164000,38.08,59.65,53.20
2,S0003,2025-01-01 02:00:00+00:00,76.93,66.25,66.15,72.07,69.23,60.51,70.14,66.78,...,70.12,69.097,73.906667,68.460,71.455,77.97,71.356667,27.40,76.02,76.02
3,S0004,2025-01-01 03:00:00+00:00,84.16,77.13,80.88,93.83,85.58,78.95,93.06,86.86,...,84.95,84.094,84.443333,89.960,80.245,87.34,84.968000,15.64,88.71,87.82
4,S0005,2025-01-01 04:00:00+00:00,59.81,55.38,73.78,49.15,44.42,58.36,63.49,62.41,...,60.87,57.505,60.170000,62.950,54.125,67.47,60.308000,35.76,62.05,59.82

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

model_features = [
    "Programming",
    "DSA",
    "DBMS",
    "Computer_Networks",
    "Operating_Systems",
    "Web_Development",
    "Data_Analytics",
    "AI_ML",
    "Cloud_Computing",
    "Cybersecurity",
    "Problem_Solving",
    "Aptitude",
    "Communication",
    "Teamwork",
    "Git_GitHub",
    "technical_skill_average",
    "programming_problem_solving",
    "data_ai_average",
    "cloud_security_average",
    "soft_skill_average",
    "overall_skill_average",
    "overall_industry_gap",
    "curriculum_alignment_score",
    "industry_alignment_score"
]

X = historical_df[model_features]
y = df["Skill_Gap_Category"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

model = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("================================")
print("MODEL RESULTS")
print("================================")
print("Accuracy:", accuracy)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

================================
MODEL RESULTS
================================
Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

    High Gap       1.00      1.00      1.00        72
     Low Gap       1.00      1.00      1.00        20
  Medium Gap       1.00      1.00      1.00        68

    accuracy                           1.00       160
   macro avg       1.00      1.00      1.00       160
weighted avg       1.00      1.00      1.00       160

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [16]:
from datetime import timedelta

start_time = feature_df["event_timestamp"].min().to_pydatetime()

end_time = (
    feature_df["event_timestamp"].max()
    + timedelta(hours=1)
).to_pydatetime()

print("Materializing from:", start_time)
print("Materializing until:", end_time)

store.materialize(
    start_time,
    end_time
)

print("================================")
print("MATERIALIZATION SUCCESSFUL")
print("================================")

Materializing from: 2025-01-01 00:00:00
Materializing until: 2025-02-03 08:00:00
Materializing 1 feature views from 2025-01-01 00:00:00+00:00 to 2025-02-03 08:00:00+00:00 into the sqlite online store.

student_skill_features:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

================================
MATERIALIZATION SUCCESSFUL
================================

In [17]:
online_features = store.get_online_features(
    features=feature_refs,
    entity_rows=[
        {"student_id": "S0001"}
    ]
).to_dict()

print("================================")
print("ONLINE FEATURE OUTPUT")
print("================================")

for key, value in online_features.items():
    print(key, ":", value)

================================
ONLINE FEATURE OUTPUT
================================
student_id : ['S0001']
DBMS : [62.459999084472656]
Programming : [82.4000015258789]
soft_skill_average : [77.25]
DSA : [68.30999755859375]
technical_skill_average : [69.05500030517578]
Operating_Systems : [59.18000030517578]
Problem_Solving : [64.61000061035156]
Cloud_Computing : [68.20999908447266]
cloud_security_average : [66.93499755859375]
Teamwork : [82.12000274658203]
data_ai_average : [69.59500122070312]
Data_Analytics : [68.26000213623047]
Git_GitHub : [81.52999877929688]
Aptitude : [51.18000030517578]
industry_alignment_score : [72.87999725341797]
AI_ML : [70.93000030517578]
Communication : [72.37999725341797]
overall_skill_average : [69.4913330078125]
Cybersecurity : [65.66000366210938]
Computer_Networks : [69.62000274658203]
Web_Development : [75.5199966430664]
overall_industry_gap : [36.7400016784668]
curriculum_alignment_score : [66.66999816894531]
programming_problem_solving : [71.77333068847656]

In [18]:
# Convert Feast online features into a DataFrame

online_row = {}

for key, value in online_features.items():
    if isinstance(value, list):
        online_row[key] = value[0]
    else:
        online_row[key] = value

online_df = pd.DataFrame([online_row])

# Prepare model input
prediction_input = online_df.reindex(
    columns=model_features
)

# Make prediction
prediction = model.predict(prediction_input)

print("================================")
print("FINAL PREDICTION")
print("================================")
print("Student ID: S0001")
print("Predicted Skill Gap:", prediction[0])
print("================================")

================================
FINAL PREDICTION
================================
Student ID: S0001
Predicted Skill Gap: Medium Gap
================================

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)